griffith/config/routes.rb
Rails.application.routes.draw do
  get 'pages/about_us'
  get 'pages/courses'
  get 'pages/location'
  get 'pages/contact_us'
  get 'pages/home'

  get 'about_us' => 'pages#about_us'
  get 'courses' => 'pages#courses'
  get 'location' => 'pages#location'
  get 'contact_us' => 'pages#contact_us'
  get 'home' => 'pages#home'

  root 'pages#home'

end

griffith/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

griffith/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end
  def courses
  end
  def location
  end
  def contact_us
  end
  def home
  end
end

griffith/app/helpers/application_helper.rb
module ApplicationHelper
end

griffith/app/helpers/pages_helper.rb
module PagesHelper
end

griffith/app/views/layouts/_menu.html.erb
<%= link_to 'About Us', about_us_path() %>
<%= link_to 'Courses', courses_path() %>
<%= link_to 'Contact Us', contact_us_path() %>
<%= link_to 'Location', location_path() %>
<%= link_to 'Home', home_path() %>

griffith/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) + " | " %>Griffith College</title>
  <%= stylesheet_link_tag    'pages', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/menu'  %>

<%= yield %>

</body>
</html>

griffith/app/views/pages/about_us.html.erb
<% content_for :title, 'About Us Page' %>

<h1>About Griffith</h1>
<p> Griffith College is Ireland's leading private college with campuses in Cork, Dublin and Limerick </p>

<p>With over 7,000 students at its campuses in Dublin, Cork and Limerick, Griffith College is the ideal choice for students seeking a strong education and a vibrant college life. Each campus is centrally located, meaning you have a wide variety of amenities and facilities on your doorstep, and with a large selection of clubs and societies, from football and basketball to film and photography, there are plenty of ways to get to know your fellow students!</p>

griffith/app/views/pages/contact_us.html.erb
<% content_for :title, 'Contact Us Page' %>

<h1>Contact us</h1>

<p>Do you have a query about one of our courses? Fill in the form below and we’ll be delighted to assist.</p>

<h6>Cork</h6>
<ul>
  <li>Griffith College Cork, Wellington Road, Cork.</li>
  <li>Phone: +353 21 4507027</li>
  <li>Email: admissions@gcc.ie</li>
</ul>

<h6>Dublin</h6>
<ul>
  <li>Griffith College Dublin, South Circular Road, Dublin 8, Dublin.</li>
  <li>Phone: +353 1 415 04 00</li>
  <li>Email: admissions@gcd.ie</li>
</ul>

<h6>Limerick</h6>
<ul>
  <li>Griffith College Limerick, O'Connell Avenue, Limerick City, Limerick.</li>
  <li>Phone: +353 61 310031</li>
  <li>Email: admissions@gcl.ie</li>
</ul>

griffith/app/views/pages/courses.html.erb
<% content_for :title, 'Courses Page' %>

<h1>Courses List</h1>
<ul>
  <li>Business</li>
  <li>Computing</li>
  <li>Design</li>
  <li>Journalism & Media Communications</li>
  <li>Law</li>
</ul>

griffith/app/views/pages/home.html.erb
<% content_for :title, 'Home Page' %>

<%= image_tag "GCD.jpg", :height => 127, :width => 212 %>

<h1>Welcome to Griffith College</h1>
<p>Welcome to the website of Griffith College.</p>

griffith/app/views/pages/location.html.erb
<% content_for :title, 'Location Page' %>

<h1>Our campuses</h1>
<p>Established in 1974, Griffith College provides a wide range of full and part-time certificate, diploma, degree and postgraduate courses and is home to over 7,000 students. Our campuses are easily accessible via car and public transport and centrally located within each city, so you have a wide range of amenities on your doorstep. Each campus has its own unique history and character. For more information on our locations in Cork, Dublin and Limerick please cilck on Contact page.</p>